services:
  hls-proxy:
    build: .
    image: maki-hls-proxy-lightest
    container_name: maki-hls-proxy-lightest
    ports:
      - "80:80"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./maki-hls-proxy-cache:/cache
